version: '3'
services:
  server:
    build:
      context: ../../../
      dockerfile: etc/environments/local/Dockerfile
    env_file: ../../../.env
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../../../src:/app/src

  tsapi-mongodb:
    image: "mongo"
    command: mongod --port ${MONGODB_PORT}
    env_file: ../../../.env
    restart: always
    logging:
      driver: none
    volumes:
     - ./volumes/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGODB_GUI_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: tsapi-mongodb
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
